num = int(input("Digte um numero: "))
num2 = int(input("Digite mais um numero: "))
print(f"{num} + {num2} = ", num + num2)
print(f"{num} - {num2} = ", num - num2)
print(f"{num} * {num2} = ", num * num2)
print(f"{num} / {num2} = ", num / num2)